Add Zarr to the ideas list for GSoC 2024
numfocus/gsoc pull request #454
Opened 2024-02-05 23:36 UTC by MSanKeys963

2024-02-05 23:54 UTC, henrykironde requested changes
Please update the spreadsheet. I sent it to the mentors mailing list.

2024-02-06 00:09 UTC, MSanKeys963 commented
> Please update the spreadsheet. I sent it to the mentors mailing list.

Done. 💯

2024-02-06 00:29 UTC, henrykironde approved these changes

2024-02-06 00:30 UTC, merged

2024-04-26 11:45 UTC, MSanKeys963 commented
Hi @henrykironde!

I'm sorry for the delay.
@akshaysubr and @decryptofy have filled out the form.